export const getRandomPassage = (difficulty) => {

  let getCusomPara = localStorage.getItem("customPara")?.trim() || "No custom paragraph has been set.";

  const paragraphs = {
    easy: "The sun is shining brightly in the sky today. Birds are flying around, chirping happily. The trees sway gently in the breeze, their leaves rustling. The grass is green, and it looks like a perfect day for a picnic. People are walking along the paths, enjoying the weather. Children are playing in the park, laughing and running after each other. Nearby, a dog is chasing a ball. The whole scene is peaceful and relaxing. I feel happy just watching everything around me. It is a wonderful day outside. I went to the grocery store to buy some food. The aisles were full of people shopping for dinner. I picked up some apples, oranges, and bananas. There were also tomatoes, cucumbers, and lettuce for the salad. The store had a lot of fresh produce, and the shelves were well stocked. I also grabbed some milk and bread. The checkout lines were a bit long, but I didn’t mind. After paying, I walked back home. It was a short walk, but I felt good knowing I had everything I needed for the week ahead.",
    medium:
      "Typing practice is a skill that can significantly improve your productivity. It allows you to work faster and more efficiently on computers. By focusing on accuracy and speed, you can reduce errors and save time. Regular practice helps to build muscle memory, which makes typing feel more natural over time. The more you practice, the easier it becomes to type quickly without looking at the keys. Whether you are writing emails, coding, or drafting documents, being able to type fast is an essential skill in today’s world. The beach was a beautiful sight, with golden sands stretching out into the distance. The sky was clear, and the bright sun reflected off the calm ocean waves. A gentle breeze carried the salty scent of the sea, making everything feel fresh. People were walking along the shoreline, their footprints leaving a temporary mark on the sand. The sound of the waves crashing against the shore created a soothing rhythm, and the occasional call of a seagull added to the peaceful atmosphere. I walked along the water’s edge, feeling the cool water wash over my feet and enjoying the serenity of the moment.",
    hard: "In an increasingly interconnected world, the ability to process vast amounts of information quickly and efficiently has become crucial. Data is constantly being generated, from social media interactions to online purchases, and understanding how to interpret and act upon this data is an essential skill. Companies now rely on sophisticated algorithms and machine learning models to analyze trends and make informed decisions. However, as technology advances, so does the need for ethical considerations in data collection and use. Striking a balance between innovation and privacy is a challenge that businesses and governments must navigate in the coming years. The concept of time has fascinated philosophers for centuries. It is something that governs our daily lives, yet it is intangible, often defying our attempts to truly understand it. Some theories suggest that time is an illusion, merely a construct of our perception. Others believe that time flows linearly, from past to present to future, and that our experiences are bound by this progression. No matter how we perceive it, time continues to influence everything we do, shaping our memories, our actions, and even our future decisions. The way we think about time affects our understanding of life itself.",
    Custom: getCusomPara,
  };

  return paragraphs[difficulty] || paragraphs.easy;
};
